# Generated by Django 4.2 on 2026-04-07 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_payment_status_order_shipping_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('mock', '模拟支付')], default='alipay', max_length=20, verbose_name='支付方式')),
                ('trade_no', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='支付平台交易号')),
                ('out_trade_no', models.CharField(max_length=64, unique=True, verbose_name='商户订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('expired', '已过期'), ('failed', '支付失败'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='支付状态')),
                ('qr_code', models.TextField(blank=True, null=True, verbose_name='支付二维码')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('paid_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='orders.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '支付交易记录',
                'verbose_name_plural': '支付交易记录',
                'db_table': 'payment_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
