# Generated by Django 4.2 on 2026-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymenttransaction_reconcile_tracking'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_method', 'status', 'expire_time'], name='idx_pay_reconcile_scan'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order', 'status', '-created_at'], name='idx_pay_order_status'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', '-created_at'], name='idx_pay_status_created'),
        ),
    ]
