# Generated by Django 4.2 on 2026-04-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付')], default='pending', max_length=20, verbose_name='支付状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_company',
            field=models.CharField(blank=True, choices=[('sf', '顺丰速运'), ('zto', '中通快递'), ('yto', '圆通速递'), ('sto', '申通快递'), ('yunda', '韵达速递')], max_length=20, verbose_name='快递公司'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('not_shipped', '未发货'), ('shipped', '已发货'), ('in_transit', '运输中'), ('arrived', '已到达'), ('signed', '已签收')], default='not_shipped', max_length=20, verbose_name='物流状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='快递单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='trade_no',
            field=models.CharField(blank=True, max_length=128, verbose_name='第三方交易号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('mock', '模拟支付')], max_length=20, verbose_name='支付方式'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_orde_payment_bc131d_idx'),
        ),
    ]
