# Generated by Django 4.2 on 2026-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_status_order_shipping_company_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'payment_status', 'status', '-created_at'], name='idx_order_user_pay_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', 'status', 'expires_at'], name='idx_order_expire_scan'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_no'], name='idx_order_tracking_no'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='idx_order_item_order_product'),
        ),
    ]
