# Generated by Django 4.2 on 2026-05-09 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0004_order_idx_order_user_pay_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=100, verbose_name='Idempotency key')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='processing', max_length=16, verbose_name='Status')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_records', to='orders.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_submissions', to='users.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order submission',
                'verbose_name_plural': 'Order submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='ordersubmission',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='uniq_order_submission_user_key'),
        ),
        migrations.AddIndex(
            model_name='ordersubmission',
            index=models.Index(fields=['user', 'status', '-created_at'], name='idx_order_submit_user_status'),
        ),
    ]
