# Generated by Django 4.2 on 2026-04-16 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeckillActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Activity name')),
                ('seckill_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Seckill price')),
                ('total_stock', models.PositiveIntegerField(default=0, verbose_name='Total stock')),
                ('reserved_stock', models.PositiveIntegerField(default=0, verbose_name='Reserved stock')),
                ('per_user_limit', models.PositiveIntegerField(default=1, verbose_name='Per user limit')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('online', 'Online'), ('ended', 'Ended')], default='draft', max_length=20, verbose_name='Status')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('start_at', models.DateTimeField(verbose_name='Start time')),
                ('end_at', models.DateTimeField(verbose_name='End time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seckill_activities', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Seckill activity',
                'verbose_name_plural': 'Seckill activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeckillReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='reserved', max_length=20, verbose_name='Status')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Idempotency key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='seckill.seckillactivity', verbose_name='Activity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seckill_reservations', to='products.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seckill_reservations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Seckill reservation',
                'verbose_name_plural': 'Seckill reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='seckillreservation',
            index=models.Index(fields=['activity', 'status', '-created_at'], name='seckill_sec_activit_6d0ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='seckillreservation',
            index=models.Index(fields=['user', '-created_at'], name='seckill_sec_user_id_3c1002_idx'),
        ),
        migrations.AddIndex(
            model_name='seckillactivity',
            index=models.Index(fields=['status', 'is_enabled', 'start_at'], name='seckill_sec_status_adc55d_idx'),
        ),
        migrations.AddIndex(
            model_name='seckillactivity',
            index=models.Index(fields=['product', '-created_at'], name='seckill_sec_product_53b759_idx'),
        ),
    ]
