# Generated by Django 4.2 on 2026-04-16 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_status_order_shipping_company_and_more'),
        ('seckill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seckillreservation',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seckill_reservation', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='seckillreservation',
            name='reserved_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Reserved expires at'),
        ),
        migrations.AlterField(
            model_name='seckillreservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('ordered', 'Ordered'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='reserved', max_length=20, verbose_name='Status'),
        ),
    ]
