# Generated by Django 4.2 on 2026-04-16 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seckill', '0002_seckillreservation_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeckillAdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_activity', 'Create activity'), ('update_activity', 'Update activity'), ('delete_activity', 'Delete activity'), ('adjust_stock', 'Adjust stock'), ('adjust_price', 'Adjust price'), ('change_status', 'Change status'), ('release_reservation', 'Release reservation')], max_length=40, verbose_name='Action type')),
                ('before_data', models.JSONField(blank=True, default=dict, verbose_name='Before data')),
                ('after_data', models.JSONField(blank=True, default=dict, verbose_name='After data')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_action_logs', to='seckill.seckillactivity', verbose_name='Activity')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seckill_admin_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_action_logs', to='seckill.seckillreservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Seckill admin action log',
                'verbose_name_plural': 'Seckill admin action logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='seckilladminactionlog',
            index=models.Index(fields=['action_type', '-created_at'], name='seckill_sec_action__06c793_idx'),
        ),
        migrations.AddIndex(
            model_name='seckilladminactionlog',
            index=models.Index(fields=['operator', '-created_at'], name='seckill_sec_operato_7c25f3_idx'),
        ),
        migrations.AddIndex(
            model_name='seckilladminactionlog',
            index=models.Index(fields=['activity', '-created_at'], name='seckill_sec_activit_979be5_idx'),
        ),
    ]
