# Generated by Django 4.2 on 2026-04-16 14:25

import apps.seckill.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seckill', '0003_seckilladminactionlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seckillactivity',
            name='group_id',
            field=models.CharField(db_index=True, default=apps.seckill.models.gen_group_id, max_length=36, verbose_name='Activity group id'),
        ),
    ]
