# Generated by Django 4.2 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seckill', '0004_seckillactivity_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seckillactivity',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('preheating', 'Preheating'),
                    ('online', 'Online'),
                    ('ended', 'Ended'),
                    ('offline', 'Offline'),
                ],
                default='draft',
                max_length=20,
                verbose_name='Status',
            ),
        ),
    ]
