# Generated by Django 4.2 on 2026-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seckill', '0005_alter_seckillactivity_status_choices'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='seckillactivity',
            index=models.Index(fields=['group_id', 'status', 'is_enabled'], name='idx_seckill_group_status'),
        ),
        migrations.AddIndex(
            model_name='seckillactivity',
            index=models.Index(fields=['status', 'start_at', 'end_at'], name='idx_seckill_window'),
        ),
        migrations.AddIndex(
            model_name='seckillreservation',
            index=models.Index(fields=['user', 'idempotency_key'], name='idx_seckill_user_idem'),
        ),
        migrations.AddIndex(
            model_name='seckillreservation',
            index=models.Index(fields=['status', 'reserved_expires_at'], name='idx_seckill_expire_scan'),
        ),
    ]
