# Generated by Django 4.2 on 2026-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['order_item', 'status'], name='idx_refund_item_status'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['user', 'idempotency_key'], name='idx_refund_user_idem'),
        ),
    ]
