# Generated by Django 4.2 on 2026-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'sales', 'created_at'], name='idx_product_feed_sales'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_hot', 'hot_sort_order'], name='idx_product_feed_hot'),
        ),
    ]
